version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: jammy
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mongo:latest
    restart: unless-stopped
